### PR TITLE
Requesting Code Review

### PR DESCRIPTION
**Pull request by matheus-fls**

### CODE REVIEW

**Comment by Ispirett** [comment]
Hey guys really great work on this project so far :1st_place_medal: Your positioning skills are on fire :fallen_leaf: . There some things that you have left out that's important for this project to be completed. 

 **Navigation bar**

* [x]  Use Floats or flex display for positioning items inside the navbar

  **Additional Links**
- [x] The section should be made of two parts: left side for links with images and right for links only
- [x] The left side is made of two parts: *More in Space and Cosmos* and *Editor's picks*
- [x] The left side uses `<figure>` and `<figcaption>` tags followed by the title of the articles
 - [x] `display: flex` or *float* are recommended

 **Footer**
- [x] It includes the NYTimes logo as an embedded image in the top left corner of the footer
- [x] The NYTimes logo is a link
- [x] It includes a *go to homepage* link on the top right corner of the footer
- [x] The bottom part of the footer to includes links with copyright, TOC, contacts, and help
- [x] Links should be organized using the `<ul>` tag and positioned with `display: flex` or *floats*

- [x] You can use this in you .stickler file 
`linters:
  flake8:
  eslint:
    config: "./eslint.config"
  csslint:
files:
  ignore:
    - "src/generated/*"
    - "webroot/bower_components/*" `

After these changes have been made please submit your work for another code review. Happy Coding.
Also **important note** for feature HTML projects user a feature branch instead of development you can give that branch descriptive name that describes the feature you are implementing.

**Comment by mapra99** [comment]
Ready for 2nd Review.

**Comment by bolah2009** [comment]
> Ready for 2nd Review.

Nice Job :clap:

**Review by bolah2009 — APPROVED** [review]
# Congratulations Team! :tada:

You've done an awesome Job :muscle:
The [project](https://raw.githack.com/matheus-fls/NYT-clone/development/index.html) looks good to me :clap: 

Good luck with your next project
Keep it up :star2:

Cheers
Bola

**Comment by matheus-fls** [comment]
Thanks Bola! Merging to master now and submitting the Project Completion form.

**Pull request merged**
